/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eyer_eyer_wand_editor_lib_EyerWandNative */

#ifndef _Included_com_eyer_eyer_wand_editor_lib_EyerWandNative
#define _Included_com_eyer_eyer_wand_editor_lib_EyerWandNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eyer_eyer_wand_editor_lib_EyerWandNative
 * Method:    get_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eyer_eyer_1wand_1editor_1lib_EyerWandNative_get_1version
  (JNIEnv *, jclass);

/*
 * Class:     com_eyer_eyer_wand_editor_lib_EyerWandNative
 * Method:    crop_init
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_eyer_eyer_1wand_1editor_1lib_EyerWandNative_crop_1init
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_eyer_eyer_wand_editor_lib_EyerWandNative
 * Method:    crop_uninit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_eyer_eyer_1wand_1editor_1lib_EyerWandNative_crop_1uninit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_eyer_eyer_wand_editor_lib_EyerWandNative
 * Method:    crop_get_crop_width
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_eyer_eyer_1wand_1editor_1lib_EyerWandNative_crop_1get_1crop_1width
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_eyer_eyer_wand_editor_lib_EyerWandNative
 * Method:    crop_get_crop_height
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_eyer_eyer_1wand_1editor_1lib_EyerWandNative_crop_1get_1crop_1height
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_eyer_eyer_wand_editor_lib_EyerWandNative
 * Method:    crop_crop
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_eyer_eyer_1wand_1editor_1lib_EyerWandNative_crop_1crop
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_eyer_eyer_wand_editor_lib_EyerWandNative
 * Method:    ogl_create_thread
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_eyer_eyer_1wand_1editor_1lib_EyerWandNative_ogl_1create_1thread
(JNIEnv * env, jclass, jobject surface);

/*
 * Class:     com_eyer_eyer_wand_editor_lib_EyerWandNative
 * Method:    ogl_stop_thread
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_eyer_eyer_1wand_1editor_1lib_EyerWandNative_ogl_1stop_1thread
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_eyer_eyer_wand_editor_lib_EyerWandNative
 * Method:    ogl_set_wh
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_eyer_eyer_1wand_1editor_1lib_EyerWandNative_ogl_1set_1wh
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
